name = "api"
main = "src/index.ts"
compatibility_date = "2024-12-26"
assets = { directory = "public" }

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "MY_KV"
id = "ec0296a732bb409894ddbb56d86374a3"
preview_id = "7f9ef08cf2e545959b4f044442730720"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "document-manager"
database_id = "2eb88d9d-a05c-40af-a8db-cea100a029db"
migrations_dir = "migrations"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1